
export COB_LDFLAGS=-Wl,--no-as-needed

BASEDIR = ../../..
LIXA_CONFIG = $(BASEDIR)/src/client/lixa-config
# default options, note that -g will leave intermediate files
COBCOPTS = -I ../../../src/client -L../../../src/client/.libs -llixac
COBCOPTS_PQ = $(COBCOPTS) -L../../../src/client/switch/postgresql/.libs -llixapq

CASE1000: CASE1000.cob
	cobc $(COBCOPTS) -x $^ -o $@

CASE1037: CASE1037.cob
	cobc $(COBCOPTS_PQ) -x $^ -o $@

