#Download base image ubuntu 18.04
FROM ubuntu:18.04
# Update Ubuntu Software repository
ARG DEBIAN_FRONTEND=noninteractive
# Install generic pre-requisites
RUN apt-get update && apt-get install -y apt-utils
# Install run-time pre-requisites
RUN apt-get install -y libxml2 libglib2.0 uuid-runtime
# build LIXA
ENV LIXA_DOWNLOAD_URL https://sourceforge.net/projects/lixa/files/latest/download
# @@@ temp
COPY lixa-1.7.3-dev.tar.gz /
# @@@ end temp
RUN buildDeps='curl make gcc pkg-config libxml2-dev libglib2.0-dev uuid-dev' \
	&& set -x \
	&& apt-get install -y $buildDeps --no-install-recommends \
	&& mkdir -p /lixa \
#	&& curl -sSL "$LIXA_DOWNLOAD_URL" -o lixa.tar.gz \
#	&& tar -xzf lixa.tar.gz -C /lixa \
# @@@ temp
	&& tar -xzf lixa-1.7.3-dev.tar.gz -C /lixa \
	&& rm /lixa-1.7.3-dev.tar.gz \
# @@@ end temp
#	&& rm lixa.tar.gz 
	&& cd /lixa/lixa-* \
	&& ./configure --disable-xta --disable-xta-java --disable-xta-python \
	&& make && make install \
	&& rm -rf /opt/lixa/share \
	&& rm -r /lixa \
	&& apt-get purge -y --auto-remove $buildDeps \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

